# Basic
title: Shunzi007
subtitle: Still waters run deep.
description: 我是王顺，是一名iOS开发者，Swift语言爱好者，Toastmaster会员。
welcome_message: 山不在高，有仙则名。水不在深，有龙则灵。斯是陋室，惟吾德馨。苔痕上阶绿，草色入帘青。谈笑有鸿儒，往来无白丁。可以调素琴，阅金经。无丝竹之乱耳，无案牍之劳形。南阳诸葛庐，西蜀子云亭。孔子云：“何陋之有？”
creator: <a href="https://github.com/Shunzi007">@Shunzi007</a>
url: ""

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: 我的简历, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 2834854683
    github: Shunzi007
    twitter: ShunWang007
    gplus: 107108267983477358171
    mail: shun.wang.coder@gmail.com


# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
